name: Deploy AWS S3

on:
  workflow_call:
    secrets:
      user_dockerhub:
        required: true
      token_dockerhub:
        required: true
jobs:
  docker-build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.user_dockerhub }}
        password: ${{ secrets.token_dockerhub }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: estefa932014/web:latest
